[package]
name = "mandelbrot-wgpu"
version = "0.1.0"
authors = ["Amandus Søve Thorsrud <ama.thorsrud@gmail.com>"]
edition = "2018"

[features]
default = []
double = []
vulkan = ["wgpu/vulkan"]

[dependencies]
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs", rev = "a7b0d5ae5bc0934439ef559ed145e93f0117c39a" }
winit = "0.22.0"
zerocopy = "0.3.0"
glsl-to-spirv = "0.1"
