[package]
name = "mandelbrot-wgpu"
version = "0.1.0"
authors = ["Amandus Søve Thorsrud <ama.thorsrud@gmail.com>"]
edition = "2018"

[features]
double = []

[dependencies]
wgpu = "0.7.0"
winit = "0.23.0"
futures = "0.3.8"
zerocopy = "0.3.0"

[build-dependencies]
shaderc = "0.7.0"
walkdir = "2.3.1"
